name: smartfarm
description: Smart App For Client Users

version: 1.0.1+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^1.0.2
  bloc: ^8.0.2
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  cached_network_image: ^3.2.0
  intl: ^0.17.0
  scrollable_clean_calendar: ^1.0.1
  dio: ^4.0.4
  flutter_dotenv: ^5.0.2
  get_storage: ^2.0.3
  jwt_decoder: ^2.0.1
  ringtone_player: ^0.1.1
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  path_provider: ^2.0.8
  simple_connection_checker: ^0.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  hive_generator: ^1.1.2


  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - .env
  ###############

  fonts:
    - family: AvenirNext
      fonts:
        - asset: assets/fonts/AvenirNextCyr-Regular.ttf
          weight: 400
        - asset: assets/fonts/AvenirNextCyr-Medium.ttf
          weight: 500
        - asset: assets/fonts/AvenirNextCyr-Bold.ttf
          weight: 700
        - asset: assets/fonts/AvenirNextCyr-SemiBold.ttf
          weight: 600


